// Generated by gencpp from file hand_eye/aruco_info.msg
// DO NOT EDIT!


#ifndef HAND_EYE_MESSAGE_ARUCO_INFO_H
#define HAND_EYE_MESSAGE_ARUCO_INFO_H

#include <ros/service_traits.h>


#include <hand_eye/aruco_infoRequest.h>
#include <hand_eye/aruco_infoResponse.h>


namespace hand_eye
{

struct aruco_info
{

typedef aruco_infoRequest Request;
typedef aruco_infoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct aruco_info
} // namespace hand_eye


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_eye::aruco_info > {
  static const char* value()
  {
    return "1bc8d5c8b1ad95abb0b2391cce4ff505";
  }

  static const char* value(const ::hand_eye::aruco_info&) { return value(); }
};

template<>
struct DataType< ::hand_eye::aruco_info > {
  static const char* value()
  {
    return "hand_eye/aruco_info";
  }

  static const char* value(const ::hand_eye::aruco_info&) { return value(); }
};


// service_traits::MD5Sum< ::hand_eye::aruco_infoRequest> should match
// service_traits::MD5Sum< ::hand_eye::aruco_info >
template<>
struct MD5Sum< ::hand_eye::aruco_infoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_eye::aruco_info >::value();
  }
  static const char* value(const ::hand_eye::aruco_infoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_eye::aruco_infoRequest> should match
// service_traits::DataType< ::hand_eye::aruco_info >
template<>
struct DataType< ::hand_eye::aruco_infoRequest>
{
  static const char* value()
  {
    return DataType< ::hand_eye::aruco_info >::value();
  }
  static const char* value(const ::hand_eye::aruco_infoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_eye::aruco_infoResponse> should match
// service_traits::MD5Sum< ::hand_eye::aruco_info >
template<>
struct MD5Sum< ::hand_eye::aruco_infoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_eye::aruco_info >::value();
  }
  static const char* value(const ::hand_eye::aruco_infoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_eye::aruco_infoResponse> should match
// service_traits::DataType< ::hand_eye::aruco_info >
template<>
struct DataType< ::hand_eye::aruco_infoResponse>
{
  static const char* value()
  {
    return DataType< ::hand_eye::aruco_info >::value();
  }
  static const char* value(const ::hand_eye::aruco_infoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_EYE_MESSAGE_ARUCO_INFO_H
