// Generated by gencpp from file hand_eye/eye2baseResponse.msg
// DO NOT EDIT!


#ifndef HAND_EYE_MESSAGE_EYE2BASERESPONSE_H
#define HAND_EYE_MESSAGE_EYE2BASERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_eye
{
template <class ContainerAllocator>
struct eye2baseResponse_
{
  typedef eye2baseResponse_<ContainerAllocator> Type;

  eye2baseResponse_()
    : tar_pose()  {
    }
  eye2baseResponse_(const ContainerAllocator& _alloc)
    : tar_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _tar_pose_type;
  _tar_pose_type tar_pose;





  typedef boost::shared_ptr< ::hand_eye::eye2baseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_eye::eye2baseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct eye2baseResponse_

typedef ::hand_eye::eye2baseResponse_<std::allocator<void> > eye2baseResponse;

typedef boost::shared_ptr< ::hand_eye::eye2baseResponse > eye2baseResponsePtr;
typedef boost::shared_ptr< ::hand_eye::eye2baseResponse const> eye2baseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_eye::eye2baseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_eye::eye2baseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hand_eye::eye2baseResponse_<ContainerAllocator1> & lhs, const ::hand_eye::eye2baseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.tar_pose == rhs.tar_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hand_eye::eye2baseResponse_<ContainerAllocator1> & lhs, const ::hand_eye::eye2baseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hand_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hand_eye::eye2baseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_eye::eye2baseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_eye::eye2baseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_eye::eye2baseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_eye::eye2baseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_eye::eye2baseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_eye::eye2baseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13e916f631234683424cc610f1b27a51";
  }

  static const char* value(const ::hand_eye::eye2baseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13e916f631234683ULL;
  static const uint64_t static_value2 = 0x424cc610f1b27a51ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_eye::eye2baseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_eye/eye2baseResponse";
  }

  static const char* value(const ::hand_eye::eye2baseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_eye::eye2baseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64[]   tar_pose\n"
;
  }

  static const char* value(const ::hand_eye::eye2baseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_eye::eye2baseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tar_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct eye2baseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_eye::eye2baseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_eye::eye2baseResponse_<ContainerAllocator>& v)
  {
    s << indent << "tar_pose[]" << std::endl;
    for (size_t i = 0; i < v.tar_pose.size(); ++i)
    {
      s << indent << "  tar_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.tar_pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_EYE_MESSAGE_EYE2BASERESPONSE_H
