// Generated by gencpp from file hand_eye/eye2baseRequest.msg
// DO NOT EDIT!


#ifndef HAND_EYE_MESSAGE_EYE2BASEREQUEST_H
#define HAND_EYE_MESSAGE_EYE2BASEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_eye
{
template <class ContainerAllocator>
struct eye2baseRequest_
{
  typedef eye2baseRequest_<ContainerAllocator> Type;

  eye2baseRequest_()
    : ini_pose()  {
    }
  eye2baseRequest_(const ContainerAllocator& _alloc)
    : ini_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _ini_pose_type;
  _ini_pose_type ini_pose;





  typedef boost::shared_ptr< ::hand_eye::eye2baseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_eye::eye2baseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct eye2baseRequest_

typedef ::hand_eye::eye2baseRequest_<std::allocator<void> > eye2baseRequest;

typedef boost::shared_ptr< ::hand_eye::eye2baseRequest > eye2baseRequestPtr;
typedef boost::shared_ptr< ::hand_eye::eye2baseRequest const> eye2baseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_eye::eye2baseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_eye::eye2baseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hand_eye::eye2baseRequest_<ContainerAllocator1> & lhs, const ::hand_eye::eye2baseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ini_pose == rhs.ini_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hand_eye::eye2baseRequest_<ContainerAllocator1> & lhs, const ::hand_eye::eye2baseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hand_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hand_eye::eye2baseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_eye::eye2baseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_eye::eye2baseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_eye::eye2baseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_eye::eye2baseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_eye::eye2baseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_eye::eye2baseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf5f31a4ddc2f5da7f91a45ce88ebe88";
  }

  static const char* value(const ::hand_eye::eye2baseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf5f31a4ddc2f5daULL;
  static const uint64_t static_value2 = 0x7f91a45ce88ebe88ULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_eye::eye2baseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_eye/eye2baseRequest";
  }

  static const char* value(const ::hand_eye::eye2baseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_eye::eye2baseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[]   ini_pose\n"
"\n"
;
  }

  static const char* value(const ::hand_eye::eye2baseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_eye::eye2baseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ini_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct eye2baseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_eye::eye2baseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_eye::eye2baseRequest_<ContainerAllocator>& v)
  {
    s << indent << "ini_pose[]" << std::endl;
    for (size_t i = 0; i < v.ini_pose.size(); ++i)
    {
      s << indent << "  ini_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.ini_pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_EYE_MESSAGE_EYE2BASEREQUEST_H
