// Generated by gencpp from file hand_eye/hand_eye_calibration.msg
// DO NOT EDIT!


#ifndef HAND_EYE_MESSAGE_HAND_EYE_CALIBRATION_H
#define HAND_EYE_MESSAGE_HAND_EYE_CALIBRATION_H

#include <ros/service_traits.h>


#include <hand_eye/hand_eye_calibrationRequest.h>
#include <hand_eye/hand_eye_calibrationResponse.h>


namespace hand_eye
{

struct hand_eye_calibration
{

typedef hand_eye_calibrationRequest Request;
typedef hand_eye_calibrationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct hand_eye_calibration
} // namespace hand_eye


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_eye::hand_eye_calibration > {
  static const char* value()
  {
    return "a0517a9a02aee46cf83b64864c094a8b";
  }

  static const char* value(const ::hand_eye::hand_eye_calibration&) { return value(); }
};

template<>
struct DataType< ::hand_eye::hand_eye_calibration > {
  static const char* value()
  {
    return "hand_eye/hand_eye_calibration";
  }

  static const char* value(const ::hand_eye::hand_eye_calibration&) { return value(); }
};


// service_traits::MD5Sum< ::hand_eye::hand_eye_calibrationRequest> should match
// service_traits::MD5Sum< ::hand_eye::hand_eye_calibration >
template<>
struct MD5Sum< ::hand_eye::hand_eye_calibrationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_eye::hand_eye_calibration >::value();
  }
  static const char* value(const ::hand_eye::hand_eye_calibrationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_eye::hand_eye_calibrationRequest> should match
// service_traits::DataType< ::hand_eye::hand_eye_calibration >
template<>
struct DataType< ::hand_eye::hand_eye_calibrationRequest>
{
  static const char* value()
  {
    return DataType< ::hand_eye::hand_eye_calibration >::value();
  }
  static const char* value(const ::hand_eye::hand_eye_calibrationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_eye::hand_eye_calibrationResponse> should match
// service_traits::MD5Sum< ::hand_eye::hand_eye_calibration >
template<>
struct MD5Sum< ::hand_eye::hand_eye_calibrationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_eye::hand_eye_calibration >::value();
  }
  static const char* value(const ::hand_eye::hand_eye_calibrationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_eye::hand_eye_calibrationResponse> should match
// service_traits::DataType< ::hand_eye::hand_eye_calibration >
template<>
struct DataType< ::hand_eye::hand_eye_calibrationResponse>
{
  static const char* value()
  {
    return DataType< ::hand_eye::hand_eye_calibration >::value();
  }
  static const char* value(const ::hand_eye::hand_eye_calibrationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_EYE_MESSAGE_HAND_EYE_CALIBRATION_H
