// Generated by gencpp from file hand_eye/save_pcd.msg
// DO NOT EDIT!


#ifndef HAND_EYE_MESSAGE_SAVE_PCD_H
#define HAND_EYE_MESSAGE_SAVE_PCD_H

#include <ros/service_traits.h>


#include <hand_eye/save_pcdRequest.h>
#include <hand_eye/save_pcdResponse.h>


namespace hand_eye
{

struct save_pcd
{

typedef save_pcdRequest Request;
typedef save_pcdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct save_pcd
} // namespace hand_eye


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_eye::save_pcd > {
  static const char* value()
  {
    return "019443dee1fc0f101de6cb027a41dd75";
  }

  static const char* value(const ::hand_eye::save_pcd&) { return value(); }
};

template<>
struct DataType< ::hand_eye::save_pcd > {
  static const char* value()
  {
    return "hand_eye/save_pcd";
  }

  static const char* value(const ::hand_eye::save_pcd&) { return value(); }
};


// service_traits::MD5Sum< ::hand_eye::save_pcdRequest> should match
// service_traits::MD5Sum< ::hand_eye::save_pcd >
template<>
struct MD5Sum< ::hand_eye::save_pcdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_eye::save_pcd >::value();
  }
  static const char* value(const ::hand_eye::save_pcdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_eye::save_pcdRequest> should match
// service_traits::DataType< ::hand_eye::save_pcd >
template<>
struct DataType< ::hand_eye::save_pcdRequest>
{
  static const char* value()
  {
    return DataType< ::hand_eye::save_pcd >::value();
  }
  static const char* value(const ::hand_eye::save_pcdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_eye::save_pcdResponse> should match
// service_traits::MD5Sum< ::hand_eye::save_pcd >
template<>
struct MD5Sum< ::hand_eye::save_pcdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_eye::save_pcd >::value();
  }
  static const char* value(const ::hand_eye::save_pcdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_eye::save_pcdResponse> should match
// service_traits::DataType< ::hand_eye::save_pcd >
template<>
struct DataType< ::hand_eye::save_pcdResponse>
{
  static const char* value()
  {
    return DataType< ::hand_eye::save_pcd >::value();
  }
  static const char* value(const ::hand_eye::save_pcdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_EYE_MESSAGE_SAVE_PCD_H
