// Generated by gencpp from file hand_eye/save_pcdResponse.msg
// DO NOT EDIT!


#ifndef HAND_EYE_MESSAGE_SAVE_PCDRESPONSE_H
#define HAND_EYE_MESSAGE_SAVE_PCDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hand_eye
{
template <class ContainerAllocator>
struct save_pcdResponse_
{
  typedef save_pcdResponse_<ContainerAllocator> Type;

  save_pcdResponse_()
    : done(false)  {
    }
  save_pcdResponse_(const ContainerAllocator& _alloc)
    : done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::hand_eye::save_pcdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hand_eye::save_pcdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct save_pcdResponse_

typedef ::hand_eye::save_pcdResponse_<std::allocator<void> > save_pcdResponse;

typedef boost::shared_ptr< ::hand_eye::save_pcdResponse > save_pcdResponsePtr;
typedef boost::shared_ptr< ::hand_eye::save_pcdResponse const> save_pcdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hand_eye::save_pcdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hand_eye::save_pcdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hand_eye::save_pcdResponse_<ContainerAllocator1> & lhs, const ::hand_eye::save_pcdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hand_eye::save_pcdResponse_<ContainerAllocator1> & lhs, const ::hand_eye::save_pcdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hand_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hand_eye::save_pcdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hand_eye::save_pcdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_eye::save_pcdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hand_eye::save_pcdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_eye::save_pcdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hand_eye::save_pcdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hand_eye::save_pcdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::hand_eye::save_pcdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89bb254424e4cffeULL;
  static const uint64_t static_value2 = 0xdbf494e7b0ddbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::hand_eye::save_pcdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hand_eye/save_pcdResponse";
  }

  static const char* value(const ::hand_eye::save_pcdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hand_eye::save_pcdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool  done\n"
;
  }

  static const char* value(const ::hand_eye::save_pcdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hand_eye::save_pcdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct save_pcdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hand_eye::save_pcdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hand_eye::save_pcdResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAND_EYE_MESSAGE_SAVE_PCDRESPONSE_H
