(cl:defpackage hand_eye-srv
  (:use )
  (:export
   "ARUCO_INFO"
   "<ARUCO_INFO-REQUEST>"
   "ARUCO_INFO-REQUEST"
   "<ARUCO_INFO-RESPONSE>"
   "ARUCO_INFO-RESPONSE"
   "EYE2BASE"
   "<EYE2BASE-REQUEST>"
   "EYE2BASE-REQUEST"
   "<EYE2BASE-RESPONSE>"
   "EYE2BASE-RESPONSE"
   "HAND_EYE_CALIBRATION"
   "<HAND_EYE_CALIBRATION-REQUEST>"
   "HAND_EYE_CALIBRATION-REQUEST"
   "<HAND_EYE_CALIBRATION-RESPONSE>"
   "HAND_EYE_CALIBRATION-RESPONSE"
   "SAVE_PCD"
   "<SAVE_PCD-REQUEST>"
   "SAVE_PCD-REQUEST"
   "<SAVE_PCD-RESPONSE>"
   "SAVE_PCD-RESPONSE"
  ))

